# 2.DataFrame
2차원 데이터(Series들의 모음)

## Data 준비
사전 (dict) 자료구조를 통해 생성

예) 인물 데이터

In [4]:
data = {
    '이름' : ['김동민','kimdongmin','キムドンミン'],
    '언어' : ['한글','English','日本語'],
    '글자수' : [2,7,3]
}

data

{'이름': ['김동민', 'kimdongmin', 'キムドンミン'],
 '언어': ['한글', 'English', '日本語'],
 '글자수': [2, 7, 3]}

In [6]:
data['이름']

['김동민', 'kimdongmin', 'キムドンミン']

In [7]:
data['글자수']

[2, 7, 3]

## DataFrame 객체생성

In [8]:
import pandas as pd
df=pd.DataFrame(data)

In [9]:
df

           이름       언어  글자수
0         김동민       한글    2
1  kimdongmin  English    7
2      キムドンミン      日本語    3

## 데이터 접근

In [10]:
df['이름']

0           김동민
1    kimdongmin
2        キムドンミン
Name: 이름, dtype: object

In [11]:
df['글자수']

0    2
1    7
2    3
Name: 글자수, dtype: int64

In [12]:
df[['이름','언어']]

           이름       언어
0         김동민       한글
1  kimdongmin  English
2      キムドンミン      日本語

## DataFrame 객체 생성 (index지정)

In [14]:
df=pd.DataFrame(data,index=['a','b','c'])
df

           이름       언어  글자수
a         김동민       한글    2
b  kimdongmin  English    7
c      キムドンミン      日本語    3

## DataFrame 객체생성 (Column지정)
data 중에서 원하는 column만 선택하거나, 순서 병경 가능

In [16]:
df=pd.DataFrame(data,columns=['이름','글자수'])
df

           이름  글자수
0         김동민    2
1  kimdongmin    7
2      キムドンミン    3

In [17]:
df=pd.DataFrame(data,columns=['글자수','이름'])
df

   글자수          이름
0    2         김동민
1    7  kimdongmin
2    3      キムドンミン