# 4. 파일 저장 및 열기
DataFrame 객체를 excel,csv,txt등의 형태의 파일로 저장 및 열기

In [1]:
import pandas as pd
data={
    '日本語' : ['リンゴ','オレンジ','パイナップル','イチゴ','ナシ'],
    'English' : ['apple','orange','pineapple','strawberry','pear'],
    '한글' : ['사과','오랜지','파인애플','딸기','배'],
    'kcal' : ['54','47.1','50.9','33.9','57.1']
}

df = pd.DataFrame(data,index=['no1','no2','no3','no4','no5'])
df.index.name='no'
df

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과    54
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

## 저장하기
### csv 파일로 저장

In [2]:
df.to_csv('fruit.csv',encoding='utf-8-sig')

In [3]:
df.to_csv('fruit.csv',encoding='utf-8-sig',index=False)

### 텍스트(.txt)파일로 저장

In [4]:
df.to_csv('fruit.txt',sep='\t') #tab으로 구분된 텍스트 파일

### 엘셀 파일로 저장

In [5]:
df.to_excel('fruit.xlsx')

***
## 열기
### csv 파일열기

In [6]:
df=pd.read_csv('fruit.csv')
df

      日本語     English    한글  kcal
0     リンゴ       apple    사과  54.0
1    オレンジ      orange   오랜지  47.1
2  パイナップル   pineapple  파인애플  50.9
3     イチゴ  strawberry    딸기  33.9
4      ナシ        pear     배  57.1

In [7]:
df=pd.read_csv('fruit.csv',skiprows=1)  #지정된 갯수 만큼의 row를 건너뜀
df

      リンゴ       apple    사과    54
0    オレンジ      orange   오랜지  47.1
1  パイナップル   pineapple  파인애플  50.9
2     イチゴ  strawberry    딸기  33.9
3      ナシ        pear     배  57.1

In [8]:
df=pd.read_csv('fruit.csv',skiprows=[1,3,5]) #지정된 row 제외
df

    日本語     English   한글  kcal
0  オレンジ      orange  오랜지  47.1
1   イチゴ  strawberry   딸기  33.9

In [9]:
df=pd.read_csv('fruit.csv',nrows=2) #지정된 갯수(제목비포함)만큼의 row만
df

    日本語 English   한글  kcal
0   リンゴ   apple   사과  54.0
1  オレンジ  orange  오랜지  47.1

In [10]:
df=pd.read_csv('fruit.csv',skiprows=2,nrows=2) #첫 2 row 무시, 이후 2row
df

     オレンジ      orange   오랜지  47.1
0  パイナップル   pineapple  파인애플  50.9
1     イチゴ  strawberry    딸기  33.9

### 텍스트(.txt) 파일 열기

In [11]:
df=pd.read_csv('fruit.txt',sep='\t')
df

    no     日本語     English    한글  kcal
0  no1     リンゴ       apple    사과  54.0
1  no2    オレンジ      orange   오랜지  47.1
2  no3  パイナップル   pineapple  파인애플  50.9
3  no4     イチゴ  strawberry    딸기  33.9
4  no5      ナシ        pear     배  57.1

In [12]:
df=pd.read_csv('fruit.txt',sep='\t',index_col='no')
df

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

In [13]:
df=pd.read_csv('fruit.txt',sep='\t')
df.set_index('no',inplace=True)
df

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

### 엘셀 파일 열기

In [14]:
df=pd.read_excel('fruit.xlsx')
df

    no     日本語     English    한글  kcal
0  no1     リンゴ       apple    사과  54.0
1  no2    オレンジ      orange   오랜지  47.1
2  no3  パイナップル   pineapple  파인애플  50.9
3  no4     イチゴ  strawberry    딸기  33.9
4  no5      ナシ        pear     배  57.1

In [15]:
df=pd.read_excel('fruit.xlsx',index_col='no')
df

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1