## 5. 데이터 확인

In [43]:
import pandas as pd
df= pd.read_excel('fruit.xlsx',index_col='no')
df

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

## DataFrame 확인
계산 가능한 데이터에 대해 Column 별로 데이터의 갯수, 평균, 표준편차,최소/최대값 등의 정보를 보여줌

In [44]:
df.describe()

            kcal
count   5.000000
mean   48.600000
std     9.014433
min    33.900000
25%    47.100000
50%    50.900000
75%    54.000000
max    57.100000

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, no1 to no5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   日本語      5 non-null      object
 1   English  5 non-null      object
 2   한글       5 non-null      object
 3   kcal     5 non-null      float64
dtypes: float64(1), object(3)
memory usage: 200.0+ bytes

In [46]:
df.head() #처음 5개의 row를 가져옴

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

In [47]:
df.head(3) #처음 3개의 row를 가져옴

        日本語    English    한글  kcal
no
no1     リンゴ      apple    사과  54.0
no2    オレンジ     orange   오랜지  47.1
no3  パイナップル  pineapple  파인애플  50.9

In [48]:
df.tail() #마지막 5개의 row 를 가져옴

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

In [49]:
df.tail(2) #마지막 2개의 row를 가져옴

     日本語     English  한글  kcal
no
no4  イチゴ  strawberry  딸기  33.9
no5   ナシ        pear   배  57.1

In [50]:
df.values

array([['リンゴ', 'apple', '사과', 54.0],
       ['オレンジ', 'orange', '오랜지', 47.1],
       ['パイナップル', 'pineapple', '파인애플', 50.9],
       ['イチゴ', 'strawberry', '딸기', 33.9],
       ['ナシ', 'pear', '배', 57.1]], dtype=object)

In [51]:
df.index

Index(['no1', 'no2', 'no3', 'no4', 'no5'], dtype='object', name='no')

In [52]:
df.columns

Index(['日本語', 'English', '한글', 'kcal'], dtype='object')

In [53]:
df.shape #row column 개수

(5, 4)

In [54]:
df

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

## Series 확인

In [55]:
df['kcal'].describe()

count     5.000000
mean     48.600000
std       9.014433
min      33.900000
25%      47.100000
50%      50.900000
75%      54.000000
max      57.100000
Name: kcal, dtype: float64

In [56]:
df['kcal'].min()

33.9

In [57]:
df['kcal'].max()

57.1

In [58]:
df['kcal'].nlargest(3) #큰 순서대로 3개의 데이터

no
no5    57.1
no1    54.0
no3    50.9
Name: kcal, dtype: float64

In [59]:
df['kcal'].mean() #평균

48.6

In [60]:
df['kcal'].sum()

243.0

In [61]:
df['kcal'].count()

5

In [62]:
df['日本語'].unique() # 중복제외 체크

array(['リンゴ', 'オレンジ', 'パイナップル', 'イチゴ', 'ナシ'], dtype=object)

In [63]:
df['日本語'].nunique() # 중복제외 개수

5