# 6. 데이터 선택 (기본)

In [1]:
import pandas as pd
df= pd.read_excel('fruit.xlsx',index_col='no')
df

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

## Column 선택 (label)

In [2]:
df['English']

no
no1         apple
no2        orange
no3     pineapple
no4    strawberry
no5          pear
Name: English, dtype: object

In [3]:
df[['English','日本語']]

        English     日本語
no
no1       apple     リンゴ
no2      orange    オレンジ
no3   pineapple  パイナップル
no4  strawberry     イチゴ
no5        pear      ナシ

## Column 선택 (정수 index)

In [4]:
df.columns

Index(['日本語', 'English', '한글', 'kcal'], dtype='object')

In [5]:
df.columns[0]

'日本語'

In [6]:
df.columns[3]

'kcal'

In [8]:
df[df.columns[0]]  # == df['日本語']

no
no1       リンゴ
no2      オレンジ
no3    パイナップル
no4       イチゴ
no5        ナシ
Name: 日本語, dtype: object

In [9]:
df[df.columns[-1]] # 맨 끝에 있는 값

no
no1    54.0
no2    47.1
no3    50.9
no4    33.9
no5    57.1
Name: kcal, dtype: float64

## 슬라이싱

In [10]:
df

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

In [12]:
df['kcal'][0:2] # 0~1까지 의 kcal 데이터

no
no1    54.0
no2    47.1
Name: kcal, dtype: float64

In [14]:
df[['日本語','한글']][:3] #처음 3개의 정보

        日本語    한글
no
no1     リンゴ    사과
no2    オレンジ   오랜지
no3  パイナップル  파인애플

In [15]:
df[3:] # 4~ 정보를 가져옴

     日本語     English  한글  kcal
no
no4  イチゴ  strawberry  딸기  33.9
no5   ナシ        pear   배  57.1