# 7. 데이터 선택 (Location)
이름을 이용해서 원하는 row에서 원하는 col 선택

In [1]:
import pandas as pd
df= pd.read_excel('fruit.xlsx',index_col='no')
df

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

In [3]:
df.loc['no1'] # index 1번에 해당하는 전체 데이터

日本語          リンゴ
English    apple
한글            사과
kcal        54.0
Name: no1, dtype: object

In [4]:
df.loc['no5'] # index 5번

日本語          ナシ
English    pear
한글            배
kcal       57.1
Name: no5, dtype: object

In [5]:
df.loc['no1','English'] # index 1에 해당하는 English 데이터

'apple'

In [7]:
df.loc[['no1','no4'],'日本語'] # index 1,4번에 해당하는 日本語 데이터

no
no1    リンゴ
no4    イチゴ
Name: 日本語, dtype: object

In [9]:
df.loc[['no2','no3'],['한글','kcal']] # index 2,3번에 해당하는 한글 kcal 데이터

       한글  kcal
no
no2   오랜지  47.1
no3  파인애플  50.9

In [12]:
df.loc['no1':'no4','日本語':'English'] # index 1~4까지,日本語부터 English까지

        日本語     English
no
no1     リンゴ       apple
no2    オレンジ      orange
no3  パイナップル   pineapple
no4     イチゴ  strawberry