# 8. 데이터 선택 (integer location)
위치를 이용하여 원하는 row 에서 원하는 col 선택

In [1]:
import pandas as pd
df= pd.read_excel('fruit.xlsx',index_col='no')
df

        日本語     English    한글  kcal
no
no1     リンゴ       apple    사과  54.0
no2    オレンジ      orange   오랜지  47.1
no3  パイナップル   pineapple  파인애플  50.9
no4     イチゴ  strawberry    딸기  33.9
no5      ナシ        pear     배  57.1

In [2]:
df.iloc[0] # 0번쨰 위치의 데이터

日本語          リンゴ
English    apple
한글            사과
kcal        54.0
Name: no1, dtype: object

In [4]:
df.iloc[4] # 4번째 위치의 데이터

日本語          ナシ
English    pear
한글            배
kcal       57.1
Name: no5, dtype: object

In [5]:
df.iloc[0:3] # 0~2번쨰 위치의 데이터

        日本語    English    한글  kcal
no
no1     リンゴ      apple    사과  54.0
no2    オレンジ     orange   오랜지  47.1
no3  パイナップル  pineapple  파인애플  50.9

In [7]:
df.iloc[0,1] # 0번쨰 위치의 1번째(English) 데이터

'apple'

In [9]:
df.iloc[4,3] # no5의 kcal 데이터( 4번쨰 위치의 3번쨰(kcal) 데이터)

57.1

In [10]:
df.iloc[[0,1],3] #0,1 번쨰 위치의 3번째(kcal) 데이터

no
no1    54.0
no2    47.1
Name: kcal, dtype: float64

In [15]:
df.iloc[[0,1],[1,2]] # 0,1번쨰 위치의 1,3번쨰(日本語,한글) 데이터

    English   한글
no
no1   apple   사과
no2  orange  오랜지

In [16]:
df.iloc[0:4,2:3] # 0~3번쨰 위치의 2~3번째(한글.kcal) 데이터

       한글
no
no1    사과
no2   오랜지
no3  파인애플
no4    딸기